News_MVC/News_MVC/Models/Tags.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public Tags()
        {
            this.ArticleTags = new HashSet<ArticleTags>();
        }
    
        public int TagID { get; set; }
        public string TagName { get; set; }
    
        public virtual ICollection<ArticleTags> ArticleTags { get; set; }
    }
}

News_MVC/News_MVC/Controllers/ArticleTagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using News_MVC.Models;

using PagedList;
using PagedList.Mvc;

namespace News_MVC.Controllers
{
    public class ArticleTagsController : Controller
    {
        private News_MVCEntities db = new News_MVCEntities();

        // GET: ArticleTags
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Index()
        {
            var articleTags = db.ArticleTags.Include(a => a.Articles).Include(a => a.Tags);

            return View(articleTags.ToList());
        }

        // GET: Article list by Tags
        public ActionResult TagArticleList(int? id,int? page)
        {
            var articleTags = db.ArticleTags.Include(a => a.Articles).Include(a => a.Tags);

           
            ////ViewBag.Message = "Articles by Tag " + articleTags.Where(s=> s.TagID==id).Select(s => s.Tags.TagName).First();
            //var Tag = articleTags.First(s => s.TagID == id);
            //ViewBag.Tag = Tag.Tags.TagName;

            //return View(articleTags.Where(s => s.TagID == id).ToList());
     
                var Tag = db.Tags.Find(id).TagName ;
                ViewBag.Tag = Tag;
                ViewData["Tags"] = db.Tags.ToList();

                return View(articleTags.Where(s => s.TagID == id).OrderByDescending(s => s.Articles.CreationDate).ToList().ToPagedList(page ?? 1, 10));
        }

        // GET: ArticleTags/Details/5
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleTags articleTags = db.ArticleTags.Find(id);
            if (articleTags == null)
            {
                return HttpNotFound();
            }
            return View(articleTags);
        }

        // GET: ArticleTags/Create
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Create()
        {
            ViewBag.ArticleID = new SelectList(db.Articles, "ArticleID", "ArticleName");
            ViewBag.TagID = new SelectList(db.Tags, "TagID", "TagName");
            return View();
        }

        // POST: ArticleTags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ArticleID,TagID")] ArticleTags articleTags)
        {
            if (ModelState.IsValid)
            {
                db.ArticleTags.Add(articleTags);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArticleID = new SelectList(db.Articles, "ArticleID", "AuthorID", articleTags.ArticleID);
            ViewBag.TagID = new SelectList(db.Tags, "TagID", "TagName", articleTags.TagID);
            return View(articleTags);
        }

        // GET: ArticleTags/Edit/5
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleTags articleTags = db.ArticleTags.Find(id);
            if (articleTags == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArticleID = new SelectList(db.Articles, "ArticleID", "ArticleName", articleTags.ArticleID);
            ViewBag.TagID = new SelectList(db.Tags, "TagID", "TagName", articleTags.TagID);
            return View(articleTags);
        }

        // POST: ArticleTags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ArticleID,TagID")] ArticleTags articleTags)
        {
            if (ModelState.IsValid)
            {
                db.Entry(articleTags).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArticleID = new SelectList(db.Articles, "ArticleID", "AuthorID", articleTags.ArticleID);
            ViewBag.TagID = new SelectList(db.Tags, "TagID", "TagName", articleTags.TagID);
            return View(articleTags);
        }

        // GET: ArticleTags/Edit/5
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Edit_(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleTags articleTags = db.ArticleTags.Find(id);
            if (articleTags == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArticleID = new SelectList(db.Articles, "ArticleID", "ArticleName", articleTags.ArticleID);
            ViewBag.TagID = new SelectList(db.Tags, "TagID", "TagName", articleTags.TagID);

            var tl = db.Tags.Select(a => a.TagID).ToList().Select(x => new SelectListItem()
            {
                Selected = db.Tags.Select(a => a.TagID).ToList().Contains(2),
                Text = "111",
                Value = "222"
            });
            
            var tba =articleTags.Tags.ArticleTags.Select(s=> s.Tags.TagName).ToList();
            var ls2 = new SelectList(db.Tags.Select(a => a.TagID).ToList(), "TagID", "TagName", articleTags.TagID).Select(x => new SelectListItem()
            {
                Selected = db.Tags.Select(a => a.TagID).ToList().Contains(1), //userRoles.Contains(x.Name),
                Text = x.Text,
                Value = x.Value
            });



            var ls = new SelectList(db.Tags, "TagID", "TagName", articleTags.TagID).Select(x => new SelectListItem()
            {
                Selected = x.Selected, //userRoles.Contains(x.Name),
                Text = x.Text,
                Value = x.Value
            });

            ViewData["TagID_"] = ls;

            ViewBag.Tags = db.ArticleTags.ToList();
            return View(articleTags);
        }

        // POST: ArticleTags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit_([Bind(Include = "Id,ArticleID,TagID")] ArticleTags articleTags, params int[] selectedTag)
        {
            if (ModelState.IsValid)
                {
                    foreach (var item in selectedTag)
                    {
                        articleTags.TagID = item;

                        db.Entry(articleTags).State = EntityState.Modified;
                        db.SaveChanges();
                    }           //return RedirectToAction("Index");
                    return RedirectToAction("Index");
                }
            
            ViewBag.ArticleID = new SelectList(db.Articles, "ArticleID", "AuthorID", articleTags.ArticleID);
            ViewBag.TagID = new SelectList(db.Tags, "TagID", "TagName", articleTags.TagID);
            return View(articleTags);
        }

        // GET: ArticleTags/Delete/5
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleTags articleTags = db.ArticleTags.Find(id);
            if (articleTags == null)
            {
                return HttpNotFound();
            }
            return View(articleTags);
        }

        // POST: ArticleTags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ArticleTags articleTags = db.ArticleTags.Find(id);
            db.ArticleTags.Remove(articleTags);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

News_MVC/News_MVC/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using News_MVC.Models;

namespace News_MVC.Controllers
{
    public class TagsController : Controller
    {
        private News_MVCEntities db = new News_MVCEntities();

        // GET: Tags
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: TagsList
        public ActionResult _TagsList()
        {
            return PartialView(db.Tags.ToList());
        }

        // GET: Tags/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = db.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // GET: Tags/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TagID,TagName")] Tags tags)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tags);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tags);
        }

        // GET: Tags/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = db.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TagID,TagName")] Tags tags)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tags).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tags);
        }

        // GET: Tags/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tags tags = db.Tags.Find(id);
            if (tags == null)
            {
                return HttpNotFound();
            }
            return View(tags);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tags tags = db.Tags.Find(id);
            db.Tags.Remove(tags);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

News_MVC/News_MVC/Views/Tags/Create.cshtml
@model News_MVC.Models.Tags

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tags</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TagName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TagName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TagName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

News_MVC/News_MVC/Views/Tags/Delete.cshtml
@model News_MVC.Models.Tags

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tags</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TagName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TagName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

News_MVC/News_MVC/Views/Tags/Details.cshtml
@model News_MVC.Models.Tags

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tags</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TagName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TagName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TagID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

News_MVC/News_MVC/Views/Tags/Edit.cshtml
@model News_MVC.Models.Tags

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tags</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TagID)

        <div class="form-group">
            @Html.LabelFor(model => model.TagName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TagName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TagName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

News_MVC/News_MVC/Views/Tags/Index.cshtml
@model IEnumerable<News_MVC.Models.Tags>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TagName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @*@Html.DisplayFor(modelItem => item.TagName)*@
            @Html.ActionLink(item.TagName, "TagArticleList", "ArticleTags", new { id = item.TagID }, null)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TagID }) |
            @Html.ActionLink("Details", "Details", new { id=item.TagID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TagID })
        </td>
    </tr>
}

</table>